name: 'Update a config file with values from environment'
description: 'Updates a config file with values from environment'
author: 'Sovarto GmbH'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  config-file:
    description: 'The config file in which the values should be replaced'
    required: true
  out-file:
    description: 'The file to which the updated config should be written'
    required: false
  file-type:
    description: 'The file type: env or json'
    required: true
    default: json
  environment-variables:
    description: 'The environment variables and their values to use to replace the values in the config file. Lines of format KEY=value or a JSON array of format [{"name": "KEY", "value": "value"}]'
    required: true

runs:
  using: node20
  main: dist/index.js
